package com.neueda.controller;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.neueda.domain.PaymentRecord;
import com.neueda.domain.RuleType;
import com.neueda.domain.Severity;
import com.neueda.domain.ValidationRuleRecord;
import com.neueda.dto.CreateValidationRuleRequest;
import com.neueda.dto.ValidationRuleResponse;
import com.neueda.exception.PaymentProcessingException;
import com.neueda.repository.ValidationRuleRepository;
import com.neueda.validation.RuleEngine;
import com.neueda.validation.RuleFactory;
import com.neueda.validation.rules.ValidationRule;
import com.neueda.validation.rules.ValidationRule.ValidationRuleResult;

import jakarta.validation.Valid;

/**
 * Admin REST Controller for Validation Rule Management.
 * 
 * Endpoints:
 * - POST /api/admin/validation-rules - Create new rule
 * - GET /api/admin/validation-rules - List all rules
 * - GET /api/admin/validation-rules/{id} - Get rule details
 * - PUT /api/admin/validation-rules/{id} - Update rule
 * - PATCH /api/admin/validation-rules/{id}/toggle - Toggle active status
 * - POST /api/admin/validation-rules/{id}/test-dry-run - Test rule without writing to DB
 */
@RestController
@RequestMapping("/api/admin/validation-rules")
public class ValidationRuleAdminController {
    
    private final ValidationRuleRepository validationRuleRepository;
    private final RuleEngine ruleEngine;
    private final RuleFactory ruleFactory;
    private final ObjectMapper objectMapper;
    
    public ValidationRuleAdminController(
        ValidationRuleRepository validationRuleRepository,
        RuleEngine ruleEngine,
        RuleFactory ruleFactory,
        ObjectMapper objectMapper
    ) {
        this.validationRuleRepository = validationRuleRepository;
        this.ruleEngine = ruleEngine;
        this.ruleFactory = ruleFactory;
        this.objectMapper = objectMapper;
    }
    
    /**
     * Create a new validation rule.
     * 
     * Request: POST /api/admin/validation-rules
     * Body: CreateValidationRuleRequest
     * 
     * Response:
     * - 201 Created: Rule created successfully
     * - 400 Bad Request: Invalid input
     * - 409 Conflict: Rule with same name already exists
     * - 500 Internal Server Error: Server error
     * 
     * @param request validation rule creation request
     * @return 201 Created with rule details
     */
    @PostMapping
    public ResponseEntity<ValidationRuleResponse> createRule(
        @Valid @RequestBody CreateValidationRuleRequest request
    ) {
        try {
            // Validate rule type
            RuleType ruleType = RuleType.valueOf(request.ruleType());
            Severity severity = Severity.valueOf(request.severity());
            
            // Create rule record
            ValidationRuleRecord rule = new ValidationRuleRecord(
                null, // id generated by DB
                request.name(),
                request.description(),
                ruleType,
                request.ruleDefinition(),
                true, // new rules are active by default
                severity,
                request.orderOfExecution(),
                LocalDateTime.now(),
                LocalDateTime.now()
            );
            
            // Save to database
            ValidationRuleRecord savedRule = validationRuleRepository.save(rule);
            
            // Return response
            return ResponseEntity.status(HttpStatus.CREATED)
                .body(toResponse(savedRule));
                
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid rule type or severity: " + e.getMessage());
        } catch (Exception e) {
            throw new PaymentProcessingException("Error creating validation rule: " + e.getMessage());
        }
    }
    
    /**
     * List all validation rules.
     * 
     * Request: GET /api/admin/validation-rules?limit=10&offset=0
     * 
     * Query Parameters:
     * - limit (optional, default 100): Max results
     * - offset (optional, default 0): Pagination offset
     * - active-only (optional, default false): Show only active rules
     * 
     * Response:
     * - 200 OK: List of validation rules
     * - 500 Internal Server Error: Server error
     * 
     * @param activeOnly show only active rules
     * @return 200 OK with list of validation rules
     */
    @GetMapping
    public ResponseEntity<List<ValidationRuleResponse>> listRules(
        @RequestParam(defaultValue = "false") boolean activeOnly
    ) {
        try {
            List<ValidationRuleRecord> rules;
            if (activeOnly) {
                rules = validationRuleRepository.findActiveRules();
            } else {
                rules = validationRuleRepository.findAll();
            }
            
            List<ValidationRuleResponse> responses = rules.stream()
                .map(this::toResponse)
                .toList();
            
            return ResponseEntity.ok(responses);
            
        } catch (Exception e) {
            throw new PaymentProcessingException("Error listing validation rules: " + e.getMessage());
        }
    }
    
    /**
     * Get validation rule details.
     * 
     * Request: GET /api/admin/validation-rules/{id}
     * 
     * Response:
     * - 200 OK: Rule details
     * - 404 Not Found: Rule does not exist
     * - 500 Internal Server Error: Server error
     * 
     * @param ruleId rule ID
     * @return 200 OK with rule details
     */
    @GetMapping("/{id}")
    public ResponseEntity<ValidationRuleResponse> getRule(
        @PathVariable(name = "id") Long ruleId
    ) {
        try {
            ValidationRuleRecord rule = validationRuleRepository.findById(ruleId)
                .orElseThrow(() -> new IllegalArgumentException("Rule not found: " + ruleId));
            
            return ResponseEntity.ok(toResponse(rule));
            
        } catch (IllegalArgumentException e) {
            throw e;
        } catch (Exception e) {
            throw new PaymentProcessingException("Error retrieving validation rule: " + e.getMessage());
        }
    }
    
    /**
     * Update a validation rule definition.
     * 
     * Request: PUT /api/admin/validation-rules/{id}
     * Body: CreateValidationRuleRequest (partial update)
     * 
     * Response:
     * - 200 OK: Rule updated successfully
     * - 404 Not Found: Rule does not exist
     * - 500 Internal Server Error: Server error
     * 
     * @param ruleId rule ID
     * @param request update request
     * @return 200 OK with updated rule details
     */
    @PutMapping("/{id}")
    public ResponseEntity<ValidationRuleResponse> updateRule(
        @PathVariable(name = "id") Long ruleId,
        @Valid @RequestBody CreateValidationRuleRequest request
    ) {
        try {
            // Retrieve existing rule
            ValidationRuleRecord existing = validationRuleRepository.findById(ruleId)
                .orElseThrow(() -> new IllegalArgumentException("Rule not found: " + ruleId));
            
            // Validate rule type and severity
            RuleType ruleType = RuleType.valueOf(request.ruleType());
            Severity severity = Severity.valueOf(request.severity());
            
            // Create updated rule
            ValidationRuleRecord updated = new ValidationRuleRecord(
                ruleId,
                request.name(),
                request.description(),
                ruleType,
                request.ruleDefinition(),
                existing.isActive(), // preserve active status
                severity,
                request.orderOfExecution(),
                existing.createdAt(),
                LocalDateTime.now()
            );
            
            // Save to database
            ValidationRuleRecord savedRule = validationRuleRepository.update(updated);
            
            return ResponseEntity.ok(toResponse(savedRule));
            
        } catch (IllegalArgumentException e) {
            throw e;
        } catch (Exception e) {
            throw new PaymentProcessingException("Error updating validation rule: " + e.getMessage());
        }
    }
    
    /**
     * Toggle rule active/inactive status.
     * 
     * Request: PATCH /api/admin/validation-rules/{id}/toggle
     * 
     * Response:
     * - 200 OK: Rule toggled successfully
     * - 404 Not Found: Rule does not exist
     * - 500 Internal Server Error: Server error
     * 
     * Toggling a rule OFF means new payments won't execute it.
     * Toggling OFF for a rule used by previous payments doesn't affect their history (immutable).
     * 
     * @param ruleId rule ID
     * @return 200 OK with updated rule details
     */
    @PatchMapping("/{id}/toggle")
    public ResponseEntity<ValidationRuleResponse> toggleRule(
        @PathVariable(name = "id") Long ruleId
    ) {
        try {
            // Retrieve existing rule
            ValidationRuleRecord existing = validationRuleRepository.findById(ruleId)
                .orElseThrow(() -> new IllegalArgumentException("Rule not found: " + ruleId));
            
            // Toggle active status
            ValidationRuleRecord toggled = new ValidationRuleRecord(
                ruleId,
                existing.name(),
                existing.description(),
                existing.ruleType(),
                existing.ruleDefinition(),
                !existing.isActive(), // toggle the status
                existing.severity(),
                existing.orderOfExecution(),
                existing.createdAt(),
                LocalDateTime.now()
            );
            
            // Save to database
            ValidationRuleRecord savedRule = validationRuleRepository.update(toggled);
            
            return ResponseEntity.ok(toResponse(savedRule));
            
        } catch (IllegalArgumentException e) {
            throw e;
        } catch (Exception e) {
            throw new PaymentProcessingException("Error toggling validation rule: " + e.getMessage());
        }
    }
    
    /**
     * Test-dry-run: Execute rule against sample payment without writing to database.
     * 
     * Useful for testing a rule before activating it, or debugging a rule.
     * 
     * Request: POST /api/admin/validation-rules/{id}/test-dry-run
     * Body: PaymentRecord as JSON sample
     * 
     * Response:
     * - 200 OK: Test result (passed/failed with error details)
     * - 404 Not Found: Rule does not exist
     * - 400 Bad Request: Invalid sample payment
     * - 500 Internal Server Error: Server error
     * 
     * @param ruleId rule ID
     * @param samplePayment sample payment to test against
     * @return 200 OK with test result
     */
    @PostMapping("/{id}/test-dry-run")
    public ResponseEntity<ValidationRuleTestResult> testRule(
        @PathVariable(name = "id") Long ruleId,
        @RequestBody PaymentTestRequest request
    ) {
        try {
            // Retrieve rule
            ValidationRuleRecord rule = validationRuleRepository.findById(ruleId)
                .orElseThrow(() -> new IllegalArgumentException("Rule not found: " + ruleId));
            
            // Create sample payment record from request
            PaymentRecord samplePayment = new PaymentRecord(
                null, // id not assigned in test
                request.idempotencyKey(),
                request.sourceAccount(),
                request.destinationAccount(),
                request.amount(),
                request.currency(),
                null, // sourceAmount - not relevant for rule testing
                null, // destinationAmount - not relevant for rule testing
                null, // exchangeRate - not relevant for rule testing
                request.status() != null ? 
                    com.neueda.domain.PaymentStatus.valueOf(request.status()) :
                    com.neueda.domain.PaymentStatus.CREATED,
                null, // errorCode
                null, // errorMessage
                0, // settlementAttemptCount
                3, // maxSettlementAttempts
                null, // lastSettlementAttemptTime
                null, // nextSettlementRetryTime
                null, // settledAt
                LocalDateTime.now(),
                LocalDateTime.now()
            );
            
            // Execute rule via RuleFactory
            com.neueda.validation.rules.ValidationRule ruleImpl = 
                ruleFactory.createRule(rule.ruleType());
            ValidationRuleResult result = ruleImpl.execute(samplePayment, rule.ruleDefinition());
            
            // Return test result (no DB write)
            return ResponseEntity.ok(new ValidationRuleTestResult(
                rule.id(),
                rule.name(),
                result.passed(),
                result.errorCode(),
                result.errorMessage(),
                result.executionTimeMs()
            ));
            
        } catch (IllegalArgumentException e) {
            throw e;
        } catch (Exception e) {
            throw new PaymentProcessingException("Error testing validation rule: " + e.getMessage());
        }
    }
    
    /**
     * Convert ValidationRuleRecord to ValidationRuleResponse DTO.
     */
    private ValidationRuleResponse toResponse(ValidationRuleRecord rule) {
        return new ValidationRuleResponse(
            rule.id(),
            rule.name(),
            rule.description(),
            rule.ruleType().name(),
            rule.ruleDefinition(),
            rule.isActive(),
            rule.severity().name(),
            rule.orderOfExecution(),
            rule.createdAt(),
            rule.updatedAt()
        );
    }
    
    /**
     * Test result for dry-run validation.
     */
    public record ValidationRuleTestResult(
        Long ruleId,
        String ruleName,
        boolean passed,
        String errorCode,
        String errorMessage,
        long executionTimeMs
    ) {
    }
    
    /**
     * Sample payment for testing rules.
     */
    public record PaymentTestRequest(
        String idempotencyKey,
        String sourceAccount,
        String destinationAccount,
        java.math.BigDecimal amount,
        String currency,
        String status // Optional: CREATED, VALIDATED, etc.
    ) {
    }
}

