package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Bulk Payment Batch domain record - immutable representation of a bulk payment batch.
 * Used for database persistence and API responses.
 * 
 * A batch contains multiple payment items, all originating from the same source account.
 * Batch-level status tracks the overall processing state.
 */
public record BulkPaymentBatchRecord(
    /**
     * Unique batch identifier (generated by database).
     */
    Long id,
    
    /**
     * User-facing batch reference (e.g., BP202608051234).
     */
    String batchReference,
    
    /**
     * Client-provided idempotency key to prevent duplicate batch uploads.
     */
    String idempotencyKey,
    
    /**
     * Source account number (12 digits) - all items in this batch must originate from this account.
     */
    String sourceAccount,
    
    /**
     * Total number of transactions in the batch.
     */
    Integer totalTransactions,
    
    /**
     * Count of successfully processed transactions.
     */
    Integer successfulTransactions,
    
    /**
     * Count of failed transactions.
     */
    Integer failedTransactions,
    
    /**
     * Sum of all transaction amounts (informational).
     */
    BigDecimal totalAmount,
    
    /**
     * Batch status in processing lifecycle.
     */
    BulkPaymentBatchStatus status,
    
    /**
     * User ID who created/uploaded the batch.
     */
    String createdBy,
    
    /**
     * Batch creation timestamp.
     */
    LocalDateTime createdAt,
    
    /**
     * Timestamp when validation phase started.
     */
    LocalDateTime validationStartedAt,
    
    /**
     * Timestamp when validation phase completed.
     */
    LocalDateTime validationCompletedAt,
    
    /**
     * Timestamp when processing phase started.
     */
    LocalDateTime processingStartedAt,
    
    /**
     * Timestamp when processing phase completed.
     */
    LocalDateTime processingCompletedAt,
    
    /**
     * Timestamp when batch fully completed.
     */
    LocalDateTime completedAt,
    
    /**
     * Last error message encountered during processing.
     */
    String lastErrorMessage
) {
    
    /**
     * Factory method for creating a new batch record.
     */
    public static BulkPaymentBatchRecord create(
        String batchReference,
        String idempotencyKey,
        String sourceAccount,
        BigDecimal totalAmount,
        Integer totalTransactions,
        String createdBy
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new BulkPaymentBatchRecord(
            null, // id generated by DB
            batchReference,
            idempotencyKey,
            sourceAccount,
            totalTransactions,
            0, // successfulTransactions starts at 0
            0, // failedTransactions starts at 0
            totalAmount,
            BulkPaymentBatchStatus.CREATED,
            createdBy,
            now,
            null, // validationStartedAt
            null, // validationCompletedAt
            null, // processingStartedAt
            null, // processingCompletedAt
            null, // completedAt
            null  // lastErrorMessage
        );
    }
    
    /**
     * Update batch status to VALIDATING.
     */
    public BulkPaymentBatchRecord withValidationStarted() {
        return new BulkPaymentBatchRecord(
            this.id,
            this.batchReference,
            this.idempotencyKey,
            this.sourceAccount,
            this.totalTransactions,
            this.successfulTransactions,
            this.failedTransactions,
            this.totalAmount,
            BulkPaymentBatchStatus.VALIDATING,
            this.createdBy,
            this.createdAt,
            LocalDateTime.now(),
            this.validationCompletedAt,
            this.processingStartedAt,
            this.processingCompletedAt,
            this.completedAt,
            this.lastErrorMessage
        );
    }
    
    /**
     * Update batch status to VALIDATED.
     */
    public BulkPaymentBatchRecord withValidationCompleted() {
        return new BulkPaymentBatchRecord(
            this.id,
            this.batchReference,
            this.idempotencyKey,
            this.sourceAccount,
            this.totalTransactions,
            this.successfulTransactions,
            this.failedTransactions,
            this.totalAmount,
            BulkPaymentBatchStatus.VALIDATED,
            this.createdBy,
            this.createdAt,
            this.validationStartedAt,
            LocalDateTime.now(),
            this.processingStartedAt,
            this.processingCompletedAt,
            this.completedAt,
            this.lastErrorMessage
        );
    }
    
    /**
     * Update batch status to PROCESSING.
     */
    public BulkPaymentBatchRecord withProcessingStarted() {
        return new BulkPaymentBatchRecord(
            this.id,
            this.batchReference,
            this.idempotencyKey,
            this.sourceAccount,
            this.totalTransactions,
            this.successfulTransactions,
            this.failedTransactions,
            this.totalAmount,
            BulkPaymentBatchStatus.PROCESSING,
            this.createdBy,
            this.createdAt,
            this.validationStartedAt,
            this.validationCompletedAt,
            LocalDateTime.now(),
            this.processingCompletedAt,
            this.completedAt,
            this.lastErrorMessage
        );
    }
    
    /**
     * Update batch status and mark processing completed.
     */
    public BulkPaymentBatchRecord withProcessingCompleted(BulkPaymentBatchStatus newStatus) {
        return new BulkPaymentBatchRecord(
            this.id,
            this.batchReference,
            this.idempotencyKey,
            this.sourceAccount,
            this.totalTransactions,
            this.successfulTransactions,
            this.failedTransactions,
            this.totalAmount,
            newStatus,
            this.createdBy,
            this.createdAt,
            this.validationStartedAt,
            this.validationCompletedAt,
            this.processingStartedAt,
            LocalDateTime.now(),
            LocalDateTime.now(),
            this.lastErrorMessage
        );
    }
    
    /**
     * Update transaction counts.
     */
    public BulkPaymentBatchRecord withUpdatedCounts(Integer successful, Integer failed) {
        return new BulkPaymentBatchRecord(
            this.id,
            this.batchReference,
            this.idempotencyKey,
            this.sourceAccount,
            this.totalTransactions,
            successful,
            failed,
            this.totalAmount,
            this.status,
            this.createdBy,
            this.createdAt,
            this.validationStartedAt,
            this.validationCompletedAt,
            this.processingStartedAt,
            this.processingCompletedAt,
            this.completedAt,
            this.lastErrorMessage
        );
    }
    
    /**
     * Update last error message.
     */
    public BulkPaymentBatchRecord withError(String errorMessage) {
        return new BulkPaymentBatchRecord(
            this.id,
            this.batchReference,
            this.idempotencyKey,
            this.sourceAccount,
            this.totalTransactions,
            this.successfulTransactions,
            this.failedTransactions,
            this.totalAmount,
            this.status,
            this.createdBy,
            this.createdAt,
            this.validationStartedAt,
            this.validationCompletedAt,
            this.processingStartedAt,
            this.processingCompletedAt,
            this.completedAt,
            errorMessage
        );
    }
}

