package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * Bulk Payment Item domain record - immutable representation of an individual transaction in a bulk batch.
 * Each item represents one payment within the batch.
 */
public record BulkPaymentItemRecord(
    /**
     * Unique item identifier within batch.
     */
    Long id,
    
    /**
     * Foreign key to parent batch.
     */
    Long batchId,
    
    /**
     * Foreign key to individual payment (NULL until payment created).
     */
    Long paymentId,
    
    /**
     * Line number in CSV (1-indexed).
     */
    Integer lineNumber,
    
    /**
     * Destination account number (12 digits).
     */
    String destinationAccount,
    
    /**
     * Transaction amount.
     */
    BigDecimal amount,
    
    /**
     * ISO 4217 currency code.
     */
    String currency,
    
    /**
     * Transaction description/memo (optional).
     */
    String description,
    
    /**
     * Item status in processing lifecycle.
     */
    BulkPaymentItemStatus status,
    
    /**
     * Error code if validation/processing failed.
     */
    String errorCode,
    
    /**
     * Detailed failure reason.
     */
    String failureReason,
    
    /**
     * Fraud score (0-100) assigned to this transaction.
     */
    BigDecimal fraudScore,
    
    /**
     * Fraud decision: APPROVED, SUSPICIOUS, REJECTED.
     */
    String fraudDecision,
    
    /**
     * JSON array of validation error details.
     */
    String validationErrors,
    
    /**
     * Rollback status if transaction was rolled back.
     */
    String rollbackStatus,
    
    /**
     * Item creation timestamp.
     */
    LocalDateTime createdAt,
    
    /**
     * Timestamp when validation completed.
     */
    LocalDateTime validatedAt,
    
    /**
     * Timestamp when payment processing started.
     */
    LocalDateTime processingStartedAt,
    
    /**
     * Timestamp when payment processing completed.
     */
    LocalDateTime completedAt
) {
    
    /**
     * Factory method for creating a new item record from CSV data.
     */
    public static BulkPaymentItemRecord create(
        Long batchId,
        Integer lineNumber,
        String destinationAccount,
        BigDecimal amount,
        String currency,
        String description
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new BulkPaymentItemRecord(
            null, // id generated by DB
            batchId,
            null, // paymentId - null until payment created
            lineNumber,
            destinationAccount,
            amount,
            currency,
            description,
            BulkPaymentItemStatus.PENDING,
            null, // errorCode
            null, // failureReason
            null, // fraudScore
            null, // fraudDecision
            null, // validationErrors
            null, // rollbackStatus
            now,
            null, // validatedAt
            null, // processingStartedAt
            null  // completedAt
        );
    }
    
    /**
     * Update item status to VALIDATING.
     */
    public BulkPaymentItemRecord withValidationStarted() {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            this.paymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            BulkPaymentItemStatus.VALIDATING,
            this.errorCode,
            this.failureReason,
            this.fraudScore,
            this.fraudDecision,
            this.validationErrors,
            this.rollbackStatus,
            this.createdAt,
            this.validatedAt,
            this.processingStartedAt,
            this.completedAt
        );
    }
    
    /**
     * Update item to VALIDATED status.
     */
    public BulkPaymentItemRecord withValidationCompleted() {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            this.paymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            BulkPaymentItemStatus.VALIDATED,
            this.errorCode,
            this.failureReason,
            this.fraudScore,
            this.fraudDecision,
            this.validationErrors,
            this.rollbackStatus,
            this.createdAt,
            LocalDateTime.now(),
            this.processingStartedAt,
            this.completedAt
        );
    }
    
    /**
     * Mark item as FAILED with error details.
     */
    public BulkPaymentItemRecord withValidationFailure(String errorCode, String failureReason, String validationErrors) {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            this.paymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            BulkPaymentItemStatus.FAILED,
            errorCode,
            failureReason,
            this.fraudScore,
            this.fraudDecision,
            validationErrors,
            this.rollbackStatus,
            this.createdAt,
            LocalDateTime.now(),
            this.processingStartedAt,
            this.completedAt
        );
    }
    
    /**
     * Update item with fraud assessment results.
     */
    public BulkPaymentItemRecord withFraudAssessment(BigDecimal fraudScore, String fraudDecision) {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            this.paymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            this.status,
            this.errorCode,
            this.failureReason,
            fraudScore,
            fraudDecision,
            this.validationErrors,
            this.rollbackStatus,
            this.createdAt,
            this.validatedAt,
            this.processingStartedAt,
            this.completedAt
        );
    }
    
    /**
     * Update item to PROCESSING status.
     */
    public BulkPaymentItemRecord withProcessingStarted(Long newPaymentId) {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            newPaymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            BulkPaymentItemStatus.PROCESSING,
            this.errorCode,
            this.failureReason,
            this.fraudScore,
            this.fraudDecision,
            this.validationErrors,
            this.rollbackStatus,
            this.createdAt,
            this.validatedAt,
            LocalDateTime.now(),
            this.completedAt
        );
    }
    
    /**
     * Mark item as SUCCESS with settlement completed.
     */
    public BulkPaymentItemRecord withProcessingSuccess() {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            this.paymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            BulkPaymentItemStatus.SUCCESS,
            null, // clear error
            null, // clear failure reason
            this.fraudScore,
            this.fraudDecision,
            this.validationErrors,
            this.rollbackStatus,
            this.createdAt,
            this.validatedAt,
            this.processingStartedAt,
            LocalDateTime.now()
        );
    }
    
    /**
     * Mark item as FAILED with processing error.
     */
    public BulkPaymentItemRecord withProcessingFailure(String errorCode, String failureReason) {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            this.paymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            BulkPaymentItemStatus.FAILED,
            errorCode,
            failureReason,
            this.fraudScore,
            this.fraudDecision,
            this.validationErrors,
            this.rollbackStatus,
            this.createdAt,
            this.validatedAt,
            this.processingStartedAt,
            LocalDateTime.now()
        );
    }
    
    /**
     * Mark item as ROLLED_BACK.
     */
    public BulkPaymentItemRecord withRollback(String rollbackStatus) {
        return new BulkPaymentItemRecord(
            this.id,
            this.batchId,
            this.paymentId,
            this.lineNumber,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.description,
            BulkPaymentItemStatus.ROLLED_BACK,
            this.errorCode,
            this.failureReason,
            this.fraudScore,
            this.fraudDecision,
            this.validationErrors,
            rollbackStatus,
            this.createdAt,
            this.validatedAt,
            this.processingStartedAt,
            LocalDateTime.now()
        );
    }
}

