package com.neueda.domain;

import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;

/**
 * Customer domain record - immutable representation of a customer profile.
 * PAN is the unique business key for ensuring one customer profile per person.
 */
public record CustomerRecord(
    /**
     * Unique customer identifier (generated by database).
     */
    Long customerId,

    /**
     * Customer full name.
     */
    @NotBlank(message = "Customer name is required")
    String name,

    /**
     * Customer date of birth.
     */
    @NotNull(message = "Date of birth is required")
    @Past(message = "Date of birth must be in the past")
    LocalDate dob,

    /**
     * Customer phone number.
     */
    @NotBlank(message = "Phone number is required")
    @Pattern(regexp = "^[0-9+() -]{7,20}$", message = "Phone number format is invalid")
    String phoneNumber,

    /**
     * Permanent Account Number - unique customer key.
     */
    @NotBlank(message = "PAN number is required")
    @Pattern(regexp = "^[A-Z]{5}[0-9]{4}[A-Z]{1}$", message = "PAN number must be a valid 10-character PAN")
    String panNumber,

    /**
     * Timestamp when the profile was created.
     */
    @NotNull(message = "Profile created timestamp is required")
    LocalDateTime profileCreated,

    /**
     * Timestamp of last update to the customer profile.
     */
    @NotNull(message = "Last updated timestamp is required")
    LocalDateTime lastUpdated,

    /**
     * Customer country.
     */
    @NotBlank(message = "Country is required")
    String country,

    /**
     * Customer profile status.
     */
    @NotNull(message = "Customer status is required")
    CustomerStatus customerAccountStatus
) {

    /**
     * Convenience constructor for creating a new customer profile.
     * PAN is treated as the unique business key, so this record is created with ACTIVE status by default.
     */
    public static CustomerRecord create(
        String name,
        LocalDate dob,
        String phoneNumber,
        String panNumber,
        String country
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new CustomerRecord(
            null,
            name,
            dob,
            phoneNumber,
            panNumber,
            now,
            now,
            country,
            CustomerStatus.ACTIVE
        );
    }

    /**
     * Creates a copy of this record with an updated status.
     */
    public CustomerRecord withStatus(CustomerStatus newStatus) {
        return new CustomerRecord(
            this.customerId,
            this.name,
            this.dob,
            this.phoneNumber,
            this.panNumber,
            this.profileCreated,
            LocalDateTime.now(),
            this.country,
            newStatus
        );
    }
}

