package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Fraud assessment immutable record.
 * Stores complete fraud detection results combining rule-based and ML-based analysis.
 */
public record FraudAssessmentRecord(
    /**
     * Unique fraud assessment identifier
     */
    Long id,
    
    /**
     * Payment ID this assessment is for
     */
    Long paymentId,
    
    /**
     * Hybrid fraud score (0-100 scale)
     * Weighted combination of rule scores and ML probability
     */
    BigDecimal hybridFraudScore,
    
    /**
     * Rule engine score (0-100)
     * Aggregated score from all triggered rules
     */
    BigDecimal ruleEngineScore,
    
    /**
     * ML model fraud probability (0-1 scale, converted to 0-100 for comparison)
     */
    BigDecimal mlFraudProbability,
    
    /**
     * Names of fraud rules that were triggered
     * Stored as JSON array string
     */
    String triggeredRulesJson,
    
    /**
     * Detailed breakdown of each rule's contribution
     * Stored as JSON object
     */
    String ruleScoresJson,
    
    /**
     * Final fraud decision: APPROVED, SUSPICIOUS, REJECTED
     */
    FraudDecision decision,
    
    /**
     * Risk level classification
     */
    FraudRiskLevel riskLevel,
    
    /**
     * Explanation text for the decision
     */
    String explanation,
    
    /**
     * Admin user who reviewed this assessment (null if auto-approved/rejected)
     */
    String reviewedBy,
    
    /**
     * Timestamp of admin review (null if auto-decision)
     */
    LocalDateTime reviewedAt,
    
    /**
     * Admin reviewer's explanation/reasoning
     */
    String reviewerNotes,
    
    /**
     * Timestamp when assessment was created
     */
    LocalDateTime createdAt,
    
    /**
     * Timestamp of last update
     */
    LocalDateTime updatedAt
) {
    
    /**
     * Create a new fraud assessment for a payment
     */
    public static FraudAssessmentRecord create(
        Long paymentId,
        BigDecimal hybridScore,
        BigDecimal ruleScore,
        BigDecimal mlProbability,
        String triggeredRules,
        String ruleScores,
        FraudDecision decision,
        FraudRiskLevel riskLevel,
        String explanation
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new FraudAssessmentRecord(
            null, // id generated by DB
            paymentId,
            hybridScore,
            ruleScore,
            mlProbability,
            triggeredRules,
            ruleScores,
            decision,
            riskLevel,
            explanation,
            null, // reviewedBy - null initially (auto-decision)
            null, // reviewedAt - null initially
            null, // reviewerNotes - no notes yet
            now,
            now
        );
    }
    
    /**
     * Mark assessment as reviewed by admin
     */
    public FraudAssessmentRecord withAdminReview(
        String reviewedByUser,
        FraudDecision adminDecision,
        String notes
    ) {
        return new FraudAssessmentRecord(
            this.id,
            this.paymentId,
            this.hybridFraudScore,
            this.ruleEngineScore,
            this.mlFraudProbability,
            this.triggeredRulesJson,
            this.ruleScoresJson,
            adminDecision,
            this.riskLevel,
            this.explanation,
            reviewedByUser,
            LocalDateTime.now(),
            notes,
            this.createdAt,
            LocalDateTime.now()
        );
    }
}

