package com.neueda.domain;

import java.time.LocalDateTime;

/**
 * Fraud Audit Event immutable record.
 * Tracks all events in the fraud assessment lifecycle for compliance and forensics.
 */
public record FraudAuditEventRecord(
    /**
     * Event record ID
     */
    Long id,
    
    /**
     * Assessment this event is associated with
     */
    Long assessmentId,
    
    /**
     * Type of event
     */
    String eventType,  // ASSESSMENT_CREATED, RULE_TRIGGERED, DECISION_MADE, REVIEW_STARTED, etc.
    
    /**
     * When event occurred
     */
    LocalDateTime eventTimestamp,
    
    /**
     * Who triggered the event
     */
    String triggeredBy,  // SYSTEM, ADMIN, SCHEDULER
    
     /**
     * User ID if triggered by administrator
     */
    String triggeredByUserId,
    
    /**
     * Event-specific data as JSON
     */
    String eventDataJson,
    
    /**
     * Creation timestamp
     */
    LocalDateTime createdAt
) {
    
    /**
     * Create a new fraud audit event
     */
    public static FraudAuditEventRecord create(
        Long assessmentId,
        String eventType,
        String triggeredBy,
        String eventData
    ) {
        return new FraudAuditEventRecord(
            null,  // id generated by DB
            assessmentId,
            eventType,
            LocalDateTime.now(),  // event timestamp
            triggeredBy,
            null,  // no user ID initially
            eventData,
            LocalDateTime.now()  // creation timestamp
        );
    }
    
    /**
     * Create a new fraud audit event triggered by admin
     */
    public static FraudAuditEventRecord createByAdmin(
        Long assessmentId,
        String eventType,
        String userId,
        String eventData
    ) {
        return new FraudAuditEventRecord(
            null,  // id generated by DB
            assessmentId,
            eventType,
            LocalDateTime.now(),
            "ADMIN",
            userId,
            eventData,
            LocalDateTime.now()
        );
    }
}

