package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * ML Model immutable record.
 * Tracks different versions of trained fraud detection models and their deployment status.
 */
public record MLModelRecord(
    /**
     * Unique model version ID
     */
    Long id,
    
    /**
     * Model name (e.g., "xgboost_paysim", "random_forest_v1")
     */
    String modelName,
    
    /**
     * Semantic version (e.g., "1.0.0", "1.1.0-rc1")
     */
    String modelVersion,
    
    /**
     * Human-readable description
     */
    String description,
    
    /**
     * ML framework type
     */
    String modelType,  // XGBOOST, RANDOM_FOREST, NEURAL_NET, ENSEMBLE
    
    /**
     * File path to serialized model
     */
    String modelPath,
    
    /**
     * When model was trained
     */
    LocalDateTime trainingDate,
    
    /**
     * Training dataset identifier
     */
    String trainingDatasetName,
    
    /**
     * Number of samples in training set
     */
    Integer trainingDatasetSize,
    
    /**
     * Model performance metrics (0-100 scale)
     */
    BigDecimal accuracyScore,
    BigDecimal precisionScore,
    BigDecimal recallScore,
    BigDecimal f1Score,
    BigDecimal aucScore,
    BigDecimal falsePositiveRate,
    BigDecimal falseNegativeRate,
    
    /**
     * Whether this model is currently deployed
     */
    Boolean isActive,
    
    /**
     * When deployed to production
     */
    LocalDateTime deploymentDate,
    
    /**
     * When superseded by newer model
     */
    LocalDateTime retirementDate,
    
    /**
     * Deployment environment
     */
    String deploymentContext,  // PROD, STAGING, TEST, DEV
    
    /**
     * Feature columns as JSON array
     */
    String featureColumnsJson,
    
    /**
     * Model hyperparameters for reproducibility
     */
    String hyperparametersJson,
    
    /**
     * Who created this model record
     */
    String createdBy,
    
    /**
     * Creation timestamp
     */
    LocalDateTime createdAt,
    
    /**
     * Last modified timestamp
     */
    LocalDateTime updatedAt
) {
    
    /**
     * Create a new ML model record for initial deployment
     */
    public static MLModelRecord create(
        String modelName,
        String modelVersion,
        String description,
        String modelType,
        String modelPath,
        LocalDateTime trainingDate,
        String trainingDatasetName,
        Integer trainingDatasetSize,
        BigDecimal accuracyScore,
        BigDecimal precisionScore,
        BigDecimal recallScore,
        BigDecimal f1Score,
        BigDecimal aucScore,
        String deploymentContext,
        String createdBy
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new MLModelRecord(
            null,  // id generated by DB
            modelName,
            modelVersion,
            description,
            modelType,
            modelPath,
            trainingDate,
            trainingDatasetName,
            trainingDatasetSize,
            accuracyScore,
            precisionScore,
            recallScore,
            f1Score,
            aucScore,
            BigDecimal.ZERO,  // falsePositiveRate
            BigDecimal.ZERO,  // falseNegativeRate
            false,  // not active initially
            null,   // deployment date set when activated
            null,   // no retirement date yet
            deploymentContext,
            "[]",   // empty feature columns initially
            "{}",   // empty hyperparameters initially
            createdBy,
            now,
            now
        );
    }
    
    /**
     * Mark this model as deployed (activated)
     */
    public MLModelRecord withDeployment() {
        return new MLModelRecord(
            this.id,
            this.modelName,
            this.modelVersion,
            this.description,
            this.modelType,
            this.modelPath,
            this.trainingDate,
            this.trainingDatasetName,
            this.trainingDatasetSize,
            this.accuracyScore,
            this.precisionScore,
            this.recallScore,
            this.f1Score,
            this.aucScore,
            this.falsePositiveRate,
            this.falseNegativeRate,
            true,  // is_active
            LocalDateTime.now(),  // deployment_date
            this.retirementDate,
            this.deploymentContext,
            this.featureColumnsJson,
            this.hyperparametersJson,
            this.createdBy,
            this.createdAt,
            LocalDateTime.now()  // updated_at
        );
    }
    
    /**
     * Mark this model as retired (replaced by newer version)
     */
    public MLModelRecord withRetirement() {
        return new MLModelRecord(
            this.id,
            this.modelName,
            this.modelVersion,
            this.description,
            this.modelType,
            this.modelPath,
            this.trainingDate,
            this.trainingDatasetName,
            this.trainingDatasetSize,
            this.accuracyScore,
            this.precisionScore,
            this.recallScore,
            this.f1Score,
            this.aucScore,
            this.falsePositiveRate,
            this.falseNegativeRate,
            false,  // is_active
            this.deploymentDate,
            LocalDateTime.now(),  // retirement_date
            this.deploymentContext,
            this.featureColumnsJson,
            this.hyperparametersJson,
            this.createdBy,
            this.createdAt,
            LocalDateTime.now()  // updated_at
        );
    }
}

