package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * ML Model Prediction immutable record.
 * Tracks individual predictions from ML models for performance monitoring and accuracy analysis.
 */
public record MLModelPredictionRecord(
    /**
     * Prediction record ID
     */
    Long id,
    
    /**
     * ML model ID that made this prediction
     */
    Long mlModelId,
    
    /**
     * Payment ID being predicted on
     */
    Long paymentId,
    
    /**
     * Associated fraud assessment ID
     */
    Long assessmentId,
    
    /**
     * Model's predicted fraud probability (0-100 scale)
     */
    BigDecimal predictedFraudProbability,
    
    /**
     * Model's confidence in its prediction (0-100)
     */
    BigDecimal predictionConfidence,
    
    /**
     * Latency of ML service response in milliseconds
     */
    Integer predictionLatencyMs,
    
    /**
     * Actual fraud outcome (populated later via feedback loop)
     */
    Boolean groundTruthFraud,
    
    /**
     * Source of ground truth information
     */
    String groundTruthSource,  // CHARGEBACK, CUSTOMER_REPORT, AUDIT
    
    /**
     * When ground truth became known
     */
    LocalDateTime groundTruthDate,
    
    /**
     * Whether prediction was correct
     */
    Boolean isCorrectPrediction,
    
    /**
     * Classification of prediction accuracy
     */
    String predictionType,  // TRUE_POSITIVE, TRUE_NEGATIVE, FALSE_POSITIVE, FALSE_NEGATIVE
    
    /**
     * Creation timestamp
     */
    LocalDateTime createdAt
) {
    
    /**
     * Create a new ML prediction record
     */
    public static MLModelPredictionRecord create(
        Long mlModelId,
        Long paymentId,
        Long assessmentId,
        BigDecimal predictedProbability,
        BigDecimal confidence,
        Integer latencyMs
    ) {
        return new MLModelPredictionRecord(
            null,  // id generated by DB
            mlModelId,
            paymentId,
            assessmentId,
            predictedProbability,
            confidence,
            latencyMs,
            null,  // ground truth not yet available
            null,  // no source yet
            null,  // no ground truth date yet
            null,  // not yet evaluated
            null,  // no classification yet
            LocalDateTime.now()  // current timestamp
        );
    }
    
    /**
     * Update prediction with actual outcome (ground truth)
     */
    public MLModelPredictionRecord withGroundTruth(
        Boolean actualFraud,
        String source,
        LocalDateTime dateDiscovered
    ) {
        boolean correct = (this.predictedFraudProbability.doubleValue() >= 50 && actualFraud) ||
                         (this.predictedFraudProbability.doubleValue() < 50 && !actualFraud);
        
        String predType;
        if (actualFraud && correct) {
            predType = "TRUE_POSITIVE";
        } else if (!actualFraud && correct) {
            predType = "TRUE_NEGATIVE";
        } else if (actualFraud && !correct) {
            predType = "FALSE_NEGATIVE";
        } else {
            predType = "FALSE_POSITIVE";
        }
        
        return new MLModelPredictionRecord(
            this.id,
            this.mlModelId,
            this.paymentId,
            this.assessmentId,
            this.predictedFraudProbability,
            this.predictionConfidence,
            this.predictionLatencyMs,
            actualFraud,
            source,
            dateDiscovered,
            correct,
            predType,
            this.createdAt
        );
    }
}

