package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;

/**
 * Payment domain record - immutable representation of a payment entity.
 * Used for database persistence and API responses.
 */
public record PaymentRecord(
    /**
     * Unique payment identifier (generated by database).
     */
    Long id,
    
    /**
     * Client-provided idempotency key (optional, for duplicate prevention).
     */
    String idempotencyKey,
    
    /**
     * Source account number (must be 12 digits).
     */
    @NotBlank(message = "Source account is required")
    String sourceAccount,
    
    /**
     * Destination account number (must be 12 digits and different from source).
     */
    @NotBlank(message = "Destination account is required")
    String destinationAccount,
    
    /**
     * Payment amount in the specified currency. Must be > 0 and <= 1,000,000.
     */
    @NotNull(message = "Amount is required")
    @Positive(message = "Amount must be greater than zero")
    BigDecimal amount,
    
    /**
     * ISO 4217 currency code (e.g., USD, EUR, GBP). Must be exactly 3 uppercase characters.
     */
    @NotBlank(message = "Currency is required")
    @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a 3-character ISO 4217 code")
    String currency,
    
    /**
     * Amount debited from source account (in source account currency).
     * Set during settlement processing.
     */
    BigDecimal sourceAmount,
    
    /**
     * Amount credited to destination account (in destination account currency).
     * Set during settlement processing after currency conversion.
     */
    BigDecimal destinationAmount,
    
    /**
     * Exchange rate applied for cross-currency transfers.
     * Set during settlement processing.
     */
    java.math.BigDecimal exchangeRate,
    
    /**
     * Current status in payment lifecycle (CREATED, VALIDATED, SENT, COMPLETED, FAILED).
     */
    @NotNull(message = "Status is required")
    PaymentStatus status,
    
    /**
     * Error code if payment failed (null if payment not failed).
     * Maps to ErrorCode enum values.
     */
    String errorCode,
    
    /**
     * Human-readable error message if payment failed (null if payment not failed).
     */
    String errorMessage,
    
    /**
     * Number of settlement processing attempts made.
     * Incremented each time settlement is attempted.
     */
    Integer settlementAttemptCount,
    
    /**
     * Maximum allowed settlement attempts before marking payment as FAILED.
     * Default: 3
     */
    Integer maxSettlementAttempts,
    
    /**
     * Timestamp of the last settlement processing attempt.
     */
    LocalDateTime lastSettlementAttemptTime,
    
    /**
     * Scheduled time for the next settlement retry if previous attempt failed.
     */
    LocalDateTime nextSettlementRetryTime,
    
    /**
     * Timestamp when payment was successfully settled (accounts debited/credited).
     */
    LocalDateTime settledAt,
    
    /**
     * Timestamp when payment was created.
     */
    @NotNull(message = "Created timestamp is required")
    LocalDateTime createdAt,
    
    /**
     * Timestamp of last update to payment record.
     */
    @NotNull(message = "Updated timestamp is required")
    LocalDateTime updatedAt
) {
    
    /**
     * Convenience constructor for creating a new payment (without id, timestamps).
     * Useful for API request processing.
     * 
     * @param idempotencyKey optional idempotency key
     * @param sourceAccount source account number
     * @param destinationAccount destination account number
     * @param amount payment amount
     * @param currency currency code
     * @return new PaymentRecord with status=CREATED, no timestamps
     */
    public static PaymentRecord create(
        String idempotencyKey,
        String sourceAccount,
        String destinationAccount,
        BigDecimal amount,
        String currency
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new PaymentRecord(
            null, // id generated by DB
            idempotencyKey,
            sourceAccount,
            destinationAccount,
            amount,
            currency,
            null, // sourceAmount - set during settlement
            null, // destinationAmount - set during settlement
            null, // exchangeRate - set during settlement
            PaymentStatus.CREATED,
            null, // no error initially
            null, // no error message initially
            0, // settlementAttemptCount starts at 0
            3, // maxSettlementAttempts default is 3
            null, // lastSettlementAttemptTime - null initially
            null, // nextSettlementRetryTime - null initially
            null, // settledAt - null initially
            now,
            now
        );
    }
    
    /**
     * Convenience constructor for creating a new payment with exchange rate information.
     * Used when payment is created with pre-calculated exchange rates from frontend.
     * 
     * @param idempotencyKey optional idempotency key
     * @param sourceAccount source account number
     * @param destinationAccount destination account number
     * @param amount payment amount in source currency
     * @param currency currency code of source account
     * @param sourceAmount amount in source account currency
     * @param destinationAmount amount in destination account currency
     * @param exchangeRate exchange rate applied
     * @return new PaymentRecord with exchange information set
     */
    public static PaymentRecord createWithExchangeRate(
        String idempotencyKey,
        String sourceAccount,
        String destinationAccount,
        BigDecimal amount,
        String currency,
        BigDecimal sourceAmount,
        BigDecimal destinationAmount,
        BigDecimal exchangeRate
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new PaymentRecord(
            null, // id generated by DB
            idempotencyKey,
            sourceAccount,
            destinationAccount,
            amount,
            currency,
            sourceAmount,
            destinationAmount,
            exchangeRate,
            PaymentStatus.CREATED,
            null, // no error initially
            null, // no error message initially
            0, // settlementAttemptCount starts at 0
            3, // maxSettlementAttempts default is 3
            null, // lastSettlementAttemptTime - null initially
            null, // nextSettlementRetryTime - null initially
            null, // settledAt - null initially
            now,
            now
        );
    }
    
    /**
     * Creates a record with FAILED status and error details.
     */
    public PaymentRecord withFailure(String errorCode, String errorMessage) {
        LocalDateTime now = LocalDateTime.now();
        return new PaymentRecord(
            this.id,
            this.idempotencyKey,
            this.sourceAccount,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.sourceAmount,
            this.destinationAmount,
            this.exchangeRate,
            PaymentStatus.FAILED,
            errorCode,
            errorMessage,
            this.settlementAttemptCount,
            this.maxSettlementAttempts,
            this.lastSettlementAttemptTime,
            this.nextSettlementRetryTime,
            this.settledAt,
            this.createdAt,
            now
        );
    }
    
    /**
     * Creates a record with updated status.
     */
    public PaymentRecord withStatus(PaymentStatus newStatus) {
        return new PaymentRecord(
            this.id,
            this.idempotencyKey,
            this.sourceAccount,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.sourceAmount,
            this.destinationAmount,
            this.exchangeRate,
            newStatus,
            this.errorCode,
            this.errorMessage,
            this.settlementAttemptCount,
            this.maxSettlementAttempts,
            this.lastSettlementAttemptTime,
            this.nextSettlementRetryTime,
            this.settledAt,
            this.createdAt,
            LocalDateTime.now()
        );
    }
    
    /**
     * Update settlement tracking fields for retry handling.
     */
    public PaymentRecord withSettlementAttempt(LocalDateTime nextRetryTime) {
        return new PaymentRecord(
            this.id,
            this.idempotencyKey,
            this.sourceAccount,
            this.destinationAccount,
            this.amount,
            this.currency,
            this.sourceAmount,
            this.destinationAmount,
            this.exchangeRate,
            this.status,
            this.errorCode,
            this.errorMessage,
            this.settlementAttemptCount + 1,
            this.maxSettlementAttempts,
            LocalDateTime.now(),
            nextRetryTime,
            this.settledAt,
            this.createdAt,
            LocalDateTime.now()
        );
    }
    
    /**
     * Mark payment as successfully settled with settlement amounts and exchange rate.
     */
    public PaymentRecord withSuccessfulSettlement(
        BigDecimal sourceAmt,
        BigDecimal destAmt,
        BigDecimal rate
    ) {
        return new PaymentRecord(
            this.id,
            this.idempotencyKey,
            this.sourceAccount,
            this.destinationAccount,
            this.amount,
            this.currency,
            sourceAmt,
            destAmt,
            rate,
            PaymentStatus.COMPLETED,
            null,
            null,
            this.settlementAttemptCount,
            this.maxSettlementAttempts,
            LocalDateTime.now(),
            null,
            LocalDateTime.now(),
            this.createdAt,
            LocalDateTime.now()
        );
    }
}

