package com.neueda.domain;

import java.time.LocalDateTime;

import jakarta.validation.constraints.NotNull;

/**
 * Payment status history record - immutable audit trail entry.
 * Every status change to a payment is recorded in the database as an immutable entry.
 * This provides a complete audit trail of the payment's lifecycle.
 */
public record PaymentStatusHistoryRecord(
    /**
     * Unique history record identifier (generated by database).
     */
    Long id,
    
    /**
     * Foreign key to the payment this history entry belongs to.
     */
    @NotNull(message = "Payment ID is required")
    Long paymentId,
    
    /**
     * Previous status before this transition (null for the initial CREATED entry).
     */
    PaymentStatus oldStatus,
    
    /**
     * New status after this transition.
     */
    @NotNull(message = "New status is required")
    PaymentStatus newStatus,
    
    /**
     * Error code if this transition resulted in FAILED status (null otherwise).
     */
    String errorCode,
    
    /**
     * Error message if this transition resulted in FAILED status (null otherwise).
     */
    String errorMessage,
    
    /**
     * Who or what triggered this status change: SYSTEM, USER, RETRY, etc.
     */
    @NotNull(message = "Triggered by is required")
    String triggeredBy,
    
    /**
     * Timestamp when this status transition occurred.
     */
    @NotNull(message = "Created timestamp is required")
    LocalDateTime createdAt
) {
    
    /**
     * Convenience constructor for creating an initial status history entry (CREATED status).
     * 
     * @param paymentId payment ID
     * @return new PaymentStatusHistoryRecord with status=CREATED, no oldStatus
     */
    public static PaymentStatusHistoryRecord createInitial(Long paymentId) {
        return new PaymentStatusHistoryRecord(
            null, // id generated by DB
            paymentId,
            null, // no previous status for initial entry
            PaymentStatus.CREATED,
            null, // no error initially
            null, // no error message initially
            "SYSTEM",
            LocalDateTime.now()
        );
    }
    
    /**
     * Convenience constructor for creating a status transition entry.
     * 
     * @param paymentId payment ID
     * @param oldStatus previous status
     * @param newStatus new status
     * @param triggeredBy who triggered the change
     * @return new PaymentStatusHistoryRecord
     */
    public static PaymentStatusHistoryRecord transition(
        Long paymentId,
        PaymentStatus oldStatus,
        PaymentStatus newStatus,
        String triggeredBy
    ) {
        return new PaymentStatusHistoryRecord(
            null, // id generated by DB
            paymentId,
            oldStatus,
            newStatus,
            null, // no error for successful transitions
            null, // no error message for successful transitions
            triggeredBy,
            LocalDateTime.now()
        );
    }
    
    /**
     * Convenience constructor for creating a failed transition entry.
     * 
     * @param paymentId payment ID
     * @param oldStatus previous status
     * @param errorCode error code
     * @param errorMessage error message
     * @param triggeredBy who triggered the change
     * @return new PaymentStatusHistoryRecord with status=FAILED
     */
    public static PaymentStatusHistoryRecord failure(
        Long paymentId,
        PaymentStatus oldStatus,
        String errorCode,
        String errorMessage,
        String triggeredBy
    ) {
        return new PaymentStatusHistoryRecord(
            null, // id generated by DB
            paymentId,
            oldStatus,
            PaymentStatus.FAILED,
            errorCode,
            errorMessage,
            triggeredBy,
            LocalDateTime.now()
        );
    }
}

