package com.neueda.domain;

import java.time.LocalDateTime;

import com.fasterxml.jackson.databind.JsonNode;

import jakarta.validation.constraints.NotNull;

/**
 * Validation result record - immutable audit log entry of a validation rule execution.
 * Every validation rule execution is logged, capturing whether it passed and how long it took.
 */
public record ValidationResultRecord(
    /**
     * Unique result record identifier (generated by database).
     */
    Long id,
    
    /**
     * Foreign key to the payment this validation was performed for.
     */
    @NotNull(message = "Payment ID is required")
    Long paymentId,
    
    /**
     * Foreign key to the validation_rules table (identifies which rule was executed).
     */
    @NotNull(message = "Validation rule ID is required")
    Long validationRuleId,
    
    /**
     * Name of the rule that was executed (denormalized from validation_rules table for readability).
     */
    @NotNull(message = "Rule name is required")
    String ruleName,
    
    /**
     * Snapshot of the rule definition at time of execution (for audit trail).
     * Stored for compliance - shows exactly what rule logic was applied.
     */
    @NotNull(message = "Rule definition is required")
    JsonNode ruleDefinition,
    
    /**
     * Whether validation passed (true) or failed (false).
     */
    boolean passed,
    
    /**
     * Error code if validation failed (null if passed).
     * Maps to ErrorCode enum values.
     */
    String errorCode,
    
    /**
     * Human-readable error message if validation failed (null if passed).
     */
    String errorMessage,
    
    /**
     * Time taken to execute this rule in milliseconds.
     * Useful for performance monitoring.
     */
    int executionTimeMs,
    
    /**
     * Timestamp when this validation was executed.
     */
    @NotNull(message = "Created timestamp is required")
    LocalDateTime createdAt
) {
    
    /**
     * Creates a successful validation result.
     * 
     * @param paymentId payment ID
     * @param validationRuleId validation rule ID
     * @param ruleName rule name
     * @param ruleDefinition rule definition JSON
     * @param executionTimeMs execution time in milliseconds
     * @return new ValidationResultRecord with passed=true and no error details
     */
    public static ValidationResultRecord success(
        Long paymentId,
        Long validationRuleId,
        String ruleName,
        JsonNode ruleDefinition,
        int executionTimeMs
    ) {
        return new ValidationResultRecord(
            null, // id generated by DB
            paymentId,
            validationRuleId,
            ruleName,
            ruleDefinition,
            true, // passed
            null, // no error
            null, // no error message
            executionTimeMs,
            LocalDateTime.now()
        );
    }
    
    /**
     * Creates a failed validation result.
     * 
     * @param paymentId payment ID
     * @param validationRuleId validation rule ID
     * @param ruleName rule name
     * @param ruleDefinition rule definition JSON
     * @param errorCode error code
     * @param errorMessage error message
     * @param executionTimeMs execution time in milliseconds
     * @return new ValidationResultRecord with passed=false and error details
     */
    public static ValidationResultRecord failure(
        Long paymentId,
        Long validationRuleId,
        String ruleName,
        JsonNode ruleDefinition,
        String errorCode,
        String errorMessage,
        int executionTimeMs
    ) {
        return new ValidationResultRecord(
            null, // id generated by DB
            paymentId,
            validationRuleId,
            ruleName,
            ruleDefinition,
            false, // failed
            errorCode,
            errorMessage,
            executionTimeMs,
            LocalDateTime.now()
        );
    }
}

