package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.PositiveOrZero;

/**
 * Account domain record - immutable representation of a bank account.
 * A customer can own multiple accounts, linked by customerId.
 */
public record AccountRecord(
	/**
	 * Unique account identifier (generated by database).
	 */
	Long accountId,

	/**
	 * Foreign key to the owning customer profile.
	 */
	@NotNull(message = "Customer ID is required")
	Long customerId,

	/**
	 * Display name for the account.
	 */
	@NotBlank(message = "Account name is required")
	String accountName,

	/**
	 * Current account balance.
	 */
	@NotNull(message = "Account balance is required")
	@PositiveOrZero(message = "Account balance cannot be negative")
	BigDecimal accountBalance,

	/**
	 * Current account status.
	 */
	@NotNull(message = "Account status is required")
	AccountStatus accountStatus,

	/**
	 * ISO 4217 currency code.
	 */
	@NotBlank(message = "Currency is required")
	@Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a 3-character ISO 4217 code")
	String currency,

	/**
	 * Date the account was opened.
	 */
	@NotNull(message = "Account opening date is required")
	@PastOrPresent(message = "Account opening date cannot be in the future")
	LocalDate accountOpeningDate,

	/**
	 * Timestamp of the last account update.
	 */
	@NotNull(message = "Last updated timestamp is required")
	LocalDateTime lastUpdated,

	/**
	 * Bank IFSC code.
	 */
	@NotBlank(message = "IFSC code is required")
	@Pattern(regexp = "^[A-Z]{4}0[A-Z0-9]{6}$", message = "IFSC code must be a valid 11-character code")
	String ifscCode,

	/**
	 * Location of the account or branch.
	 */
	@NotBlank(message = "Account location is required")
	String accountLocation,

	/**
	 * Bank name associated with the account.
	 */
	@NotBlank(message = "Bank name is required")
	String bankName,

	/**
	 * Account PIN used for payment authentication.
	 */
	@NotBlank(message = "Account PIN is required")
	String accountPin
) {

	/**
	 * Convenience constructor for creating a new account.
	 */
	public static AccountRecord create(
		Long customerId,
		String accountName,
		BigDecimal accountBalance,
		String currency,
		LocalDate accountOpeningDate,
		String ifscCode,
		String accountLocation,
		String bankName,
		String accountPin
	) {
		LocalDateTime now = LocalDateTime.now();
		return new AccountRecord(
			null,
			customerId,
			accountName,
			accountBalance,
			AccountStatus.ACTIVE,
			currency,
			accountOpeningDate,
			now,
			ifscCode,
			accountLocation,
			bankName,
			accountPin
		);
	}

	/**
	 * Creates a copy of this record with an updated status.
	 */
	public AccountRecord withStatus(AccountStatus newStatus) {
		return new AccountRecord(
			this.accountId,
			this.customerId,
			this.accountName,
			this.accountBalance,
			newStatus,
			this.currency,
			this.accountOpeningDate,
			LocalDateTime.now(),
			this.ifscCode,
			this.accountLocation,
			this.bankName,
			this.accountPin
		);
	}
}


