package com.neueda.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;

/**
 * Payment domain record - immutable representation of a payment entity.
 * Used for database persistence and API responses.
 */
public record PaymentRecord(
    /**
     * Unique payment identifier (generated by database).
     */
    Long id,
    
    /**
     * Client-provided idempotency key (optional, for duplicate prevention).
     */
    String idempotencyKey,
    
    /**
     * Source account number (must be 12 digits).
     */
    @NotBlank(message = "Source account is required")
    String sourceAccount,
    
    /**
     * Destination account number (must be 12 digits and different from source).
     */
    @NotBlank(message = "Destination account is required")
    String destinationAccount,
    
    /**
     * Payment amount in the specified currency. Must be > 0 and <= 1,000,000.
     */
    @NotNull(message = "Amount is required")
    @Positive(message = "Amount must be greater than zero")
    BigDecimal amount,
    
    /**
     * ISO 4217 currency code (e.g., USD, EUR, GBP). Must be exactly 3 uppercase characters.
     */
    @NotBlank(message = "Currency is required")
    @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a 3-character ISO 4217 code")
    String currency,
    
    /**
     * Current status in payment lifecycle (CREATED, VALIDATED, SENT, COMPLETED, FAILED).
     */
    @NotNull(message = "Status is required")
    PaymentStatus status,
    
    /**
     * Error code if payment failed (null if payment not failed).
     * Maps to ErrorCode enum values.
     */
    String errorCode,
    
    /**
     * Human-readable error message if payment failed (null if payment not failed).
     */
    String errorMessage,
    
    /**
     * Timestamp when payment was created.
     */
    @NotNull(message = "Created timestamp is required")
    LocalDateTime createdAt,
    
    /**
     * Timestamp of last update to payment record.
     */
    @NotNull(message = "Updated timestamp is required")
    LocalDateTime updatedAt
) {
    
    /**
     * Convenience constructor for creating a new payment (without id, timestamps).
     * Useful for API request processing.
     * 
     * @param idempotencyKey optional idempotency key
     * @param sourceAccount source account number
     * @param destinationAccount destination account number
     * @param amount payment amount
     * @param currency currency code
     * @return new PaymentRecord with status=CREATED, no timestamps
     */
    public static PaymentRecord create(
        String idempotencyKey,
        String sourceAccount,
        String destinationAccount,
        BigDecimal amount,
        String currency
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new PaymentRecord(
            null, // id generated by DB
            idempotencyKey,
            sourceAccount,
            destinationAccount,
            amount,
            currency,
            PaymentStatus.CREATED,
            null, // no error initially
            null, // no error message initially
            now,
            now
        );
    }
    
    /**
     * Creates a record with FAILED status and error details.
     */
    public PaymentRecord withFailure(String errorCode, String errorMessage) {
        LocalDateTime now = LocalDateTime.now();
        return new PaymentRecord(
            this.id,
            this.idempotencyKey,
            this.sourceAccount,
            this.destinationAccount,
            this.amount,
            this.currency,
            PaymentStatus.FAILED,
            errorCode,
            errorMessage,
            this.createdAt,
            now
        );
    }
    
    /**
     * Creates a record with updated status.
     */
    public PaymentRecord withStatus(PaymentStatus newStatus) {
        return new PaymentRecord(
            this.id,
            this.idempotencyKey,
            this.sourceAccount,
            this.destinationAccount,
            this.amount,
            this.currency,
            newStatus,
            this.errorCode,
            this.errorMessage,
            this.createdAt,
            LocalDateTime.now()
        );
    }
}

