package com.neueda.domain;

import java.time.LocalDateTime;

import com.fasterxml.jackson.databind.JsonNode;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Validation rule record - immutable representation of a configurable validation rule.
 * Rules are stored in the database and can be enabled/disabled or modified without code changes.
 */
public record ValidationRuleRecord(
    /**
     * Unique rule identifier (generated by database).
     */
    Long id,
    
    /**
     * Unique rule name (e.g., AMOUNT_RANGE, CURRENCY_WHITELIST).
     */
    @NotBlank(message = "Rule name is required")
    String name,
    
    /**
     * Human-readable rule description.
     */
    String description,
    
    /**
     * Rule type determines which ValidationRule implementation to use.
     * Corresponds to RuleType enum.
     */
    @NotNull(message = "Rule type is required")
    RuleType ruleType,
    
    /**
     * Rule configuration as JSON. Structure depends on rule type.
     * For AMOUNT_RANGE: { "type": "AMOUNT_RANGE", "min": 0.01, "max": 1000000.00, "message": "..." }
     * For CURRENCY_WHITELIST: { "type": "CURRENCY_WHITELIST", "allowed_currencies": [...], "message": "..." }
     */
    @NotNull(message = "Rule definition is required")
    JsonNode ruleDefinition,
    
    /**
     * Whether this rule is currently active and should be executed.
     */
    boolean isActive,
    
    /**
     * Rule severity: HARD (blocks payment) or SOFT (warning only).
     */
    @NotNull(message = "Severity is required")
    Severity severity,
    
    /**
     * Execution order for the rule engine (lower numbers execute first).
     * Allows controlling rule evaluation sequence.
     */
    int orderOfExecution,
    
    /**
     * Timestamp when rule was created.
     */
    @NotNull(message = "Created timestamp is required")
    LocalDateTime createdAt,
    
    /**
     * Timestamp of last update to rule.
     */
    @NotNull(message = "Updated timestamp is required")
    LocalDateTime updatedAt
) {
    
    /**
     * Creates a new active validation rule.
     * 
     * @param name unique rule name
     * @param description rule description
     * @param ruleType rule type
     * @param ruleDefinition rule configuration as JSON
     * @param severity rule severity (HARD or SOFT)
     * @param orderOfExecution execution order
     * @return new ValidationRuleRecord with isActive=true
     */
    public static ValidationRuleRecord create(
        String name,
        String description,
        RuleType ruleType,
        JsonNode ruleDefinition,
        Severity severity,
        int orderOfExecution
    ) {
        LocalDateTime now = LocalDateTime.now();
        return new ValidationRuleRecord(
            null, // id generated by DB
            name,
            description,
            ruleType,
            ruleDefinition,
            true, // default to active
            severity,
            orderOfExecution,
            now,
            now
        );
    }
    
    /**
     * Creates a copy of this rule with updated active status.
     */
    public ValidationRuleRecord withActiveStatus(boolean isActive) {
        return new ValidationRuleRecord(
            this.id,
            this.name,
            this.description,
            this.ruleType,
            this.ruleDefinition,
            isActive,
            this.severity,
            this.orderOfExecution,
            this.createdAt,
            LocalDateTime.now()
        );
    }
    
    /**
     * Creates a copy of this rule with updated definition.
     */
    public ValidationRuleRecord withDefinition(JsonNode newDefinition) {
        return new ValidationRuleRecord(
            this.id,
            this.name,
            this.description,
            this.ruleType,
            newDefinition,
            this.isActive,
            this.severity,
            this.orderOfExecution,
            this.createdAt,
            LocalDateTime.now()
        );
    }
}

