package com.neueda.validation;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

import com.neueda.domain.PaymentRecord;
import com.neueda.domain.ValidationResultRecord;
import com.neueda.domain.ValidationRuleRecord;
import com.neueda.validation.rules.ValidationRule;
import com.neueda.validation.rules.ValidationRule.ValidationRuleResult;

/**
 * Validation Rule Engine - orchestrates the execution of all active validation rules.
 * 
 * Process:
 * 1. Receives a payment and list of active validation rules (sorted by order_of_execution)
 * 2. For each rule in sequence:
 *    - Instantiate the rule class using RuleFactory
 *    - Execute the rule's validate() method
 *    - Record the result in a ValidationResultRecord
 * 3. Return list of all results
 * 
 * Business Logic:
 * - Rules are executed in order_of_execution sequence (lower = earlier)
 * - ALL rules are executed regardless of failures (collect all issues)
 * - If ANY HARD rule fails, payment should transition to FAILED status
 * - SOFT rule failures do not block the payment (future enhancement)
 */
@Component
public class RuleEngine {
    
    private final RuleFactory ruleFactory;
    
    public RuleEngine(RuleFactory ruleFactory) {
        this.ruleFactory = ruleFactory;
    }
    
    /**
     * Validate a payment against all provided rules.
     * 
     * @param payment payment to validate
     * @param rules list of active validation rules (should be sorted by order_of_execution)
     * @return list of ValidationResultRecord objects (one per rule executed)
     */
    public List<ValidationResultRecord> validatePayment(PaymentRecord payment, List<ValidationRuleRecord> rules) {
        List<ValidationResultRecord> results = new ArrayList<>();
        
        for (ValidationRuleRecord rule : rules) {
            try {
                // 1. Instantiate rule implementation based on rule type using RuleFactory
                ValidationRule ruleImplementation = ruleFactory.createRule(rule.ruleType());
                
                // 2. Execute the rule
                ValidationRuleResult ruleResult = ruleImplementation.execute(payment, rule.ruleDefinition());
                
                // 3. Convert to ValidationResultRecord for persistence
                ValidationResultRecord resultRecord = new ValidationResultRecord(
                    null, // id generated by DB
                    payment.id(),
                    rule.id(),
                    rule.name(),
                    rule.ruleDefinition(),
                    ruleResult.passed(),
                    ruleResult.errorCode(),
                    ruleResult.errorMessage(),
                    (int) ruleResult.executionTimeMs(),
                    java.time.LocalDateTime.now()
                );
                
                results.add(resultRecord);
                
            } catch (Exception e) {
                // If rule execution throws an exception, record it as a failure
                ValidationResultRecord errorRecord = new ValidationResultRecord(
                    null, // id generated by DB
                    payment.id(),
                    rule.id(),
                    rule.name(),
                    rule.ruleDefinition(),
                    false, // failed
                    "VALIDATION_ERROR",
                    "Exception executing rule: " + e.getMessage(),
                    0, // unknown execution time
                    java.time.LocalDateTime.now()
                );
                results.add(errorRecord);
            }
        }
        
        return results;
    }
    
    /**
     * Check if validation passed by aggregate rules logic.
     * Returns true if NO HARD rules failed, false if ANY HARD rule failed.
     * 
     * @param results list of validation results
     * @param rules list of validation rules (to check severity)
     * @return true if validation passed (no HARD rule failures), false if validation failed
     */
    public boolean hasPassedValidation(List<ValidationResultRecord> results, List<ValidationRuleRecord> rules) {
        // Create a map of rule ID to severity for quick lookup
        java.util.Map<Long, com.neueda.domain.Severity> ruleSeverityMap = new java.util.HashMap<>();
        for (ValidationRuleRecord rule : rules) {
            ruleSeverityMap.put(rule.id(), rule.severity());
        }
        
        // Check if any HARD rule failed
        for (ValidationResultRecord result : results) {
            if (!result.passed()) {
                com.neueda.domain.Severity severity = ruleSeverityMap.get(result.validationRuleId());
                if (severity == com.neueda.domain.Severity.HARD) {
                    return false; // HARD rule failed -> validation failed
                }
            }
        }
        
        return true; // No HARD rule failures -> validation passed
    }
    
    /**
     * Aggregate error message from all failed rules.
     * Creates a concise message summarizing all validation failures.
     * 
     * @param results list of validation results
     * @return aggregated error message, or null if validation passed
     */
    public String aggregateErrorMessage(List<ValidationResultRecord> results) {
        List<String> failures = new ArrayList<>();
        
        for (ValidationResultRecord result : results) {
            if (!result.passed() && result.errorMessage() != null) {
                failures.add(result.ruleName() + ": " + result.errorMessage());
            }
        }
        
        if (failures.isEmpty()) {
            return null;
        }
        
        return String.join("; ", failures);
    }
}

