package com.neueda.service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.neueda.domain.PaymentRecord;
import com.neueda.domain.PaymentStatus;
import com.neueda.domain.PaymentStatusHistoryRecord;
import com.neueda.domain.Severity;
import com.neueda.domain.ValidationResultRecord;
import com.neueda.domain.ValidationRuleRecord;
import com.neueda.repository.PaymentRepository;
import com.neueda.repository.PaymentStatusHistoryRepository;
import com.neueda.repository.ValidationResultRepository;
import com.neueda.repository.ValidationRuleRepository;
import com.neueda.validation.RuleEngine;

/**
 * Payment Service - Core business logic for payment processing.
 * 
 * Responsibilities:
 * 1. Create and validate new payments
 * 2. Handle idempotency (duplicate prevention)
 * 3. Execute validation rules via RuleEngine
 * 4. Manage payment status lifecycle
 * 5. Log validation results for audit trail
 * 6. Log status transitions for historical tracking
 */
@Service
@Transactional
public class PaymentService {
    
    private final PaymentRepository paymentRepository;
    private final ValidationRuleRepository validationRuleRepository;
    private final ValidationResultRepository validationResultRepository;
    private final PaymentStatusHistoryRepository paymentStatusHistoryRepository;
    private final RuleEngine ruleEngine;
    
    public PaymentService(
        PaymentRepository paymentRepository,
        ValidationRuleRepository validationRuleRepository,
        ValidationResultRepository validationResultRepository,
        PaymentStatusHistoryRepository paymentStatusHistoryRepository,
        RuleEngine ruleEngine
    ) {
        this.paymentRepository = paymentRepository;
        this.validationRuleRepository = validationRuleRepository;
        this.validationResultRepository = validationResultRepository;
        this.paymentStatusHistoryRepository = paymentStatusHistoryRepository;
        this.ruleEngine = ruleEngine;
    }
    
    /**
     * Create a new payment and validate it.
     * 
     * Idempotency: If idempotency key is provided and a payment with that key exists,
     * the existing payment is returned instead of creating a new one.
     * 
     * Validation: All active validation rules are executed. If any HARD rule fails,
     * the payment transitions to FAILED status.
     * 
     * Audit Trail:
     * - ValidationResultRecord created for each rule executed
     * - PaymentStatusHistoryRecord created for CREATED and FAILED statuses
     * 
     * @param payment payment record to create
     * @return created payment record with ID and status
     */
    public PaymentRecord createPayment(PaymentRecord payment) {
        // 1. Check for idempotency (duplicate prevention)
        if (payment.idempotencyKey() != null) {
            Optional<PaymentRecord> existing = paymentRepository.findByIdempotencyKey(payment.idempotencyKey());
            if (existing.isPresent()) {
                // Payment with this key already exists -> return it (idempotent response)
                return existing.get();
            }
        }
        
        // 2. Load active validation rules from database (ordered by execution sequence)
        List<ValidationRuleRecord> activeRules = validationRuleRepository.findActiveRules();
        
        // 3. Execute all validation rules via RuleEngine
        List<ValidationResultRecord> validationResults = ruleEngine.validatePayment(payment, activeRules);
        
        // 4. Determine if validation passed (no HARD rule failures)
        boolean validationPassed = ruleEngine.hasPassedValidation(validationResults, activeRules);
        
        // 5. Set payment status based on validation outcome
        PaymentRecord paymentToSave;
        if (validationPassed) {
            // All HARD rules passed -> transition to CREATED
            paymentToSave = payment.withStatus(PaymentStatus.CREATED);
        } else {
            // At least one HARD rule failed -> transition to FAILED
            String aggregatedError = ruleEngine.aggregateErrorMessage(validationResults);
            paymentToSave = payment.withFailure("VALIDATION_FAILED", aggregatedError);
        }
        
        // 6. Persist payment to database (generates ID)
        PaymentRecord savedPayment = paymentRepository.save(paymentToSave);
        
        // 7. Log all validation results for audit trail (compliance required)
        for (ValidationResultRecord result : validationResults) {
            ValidationResultRecord resultWithPaymentId = new ValidationResultRecord(
                null, // id generated by DB
                savedPayment.id(),
                result.validationRuleId(),
                result.ruleName(),
                result.ruleDefinition(),
                result.passed(),
                result.errorCode(),
                result.errorMessage(),
                result.executionTimeMs(),
                result.createdAt()
            );
            validationResultRepository.save(resultWithPaymentId);
        }
        
        // 8. Log initial status history entry (CREATED or FAILED)
        if (validationPassed) {
            // Status is CREATED
            paymentStatusHistoryRepository.save(
                PaymentStatusHistoryRecord.createInitial(savedPayment.id())
            );
            
            // 9. Auto-transition to VALIDATED (no manual step required)
            PaymentRecord validatedPayment = transitionPayment(savedPayment.id(), PaymentStatus.VALIDATED);
            return validatedPayment;
        } else {
            // Status is FAILED (due to validation)
            paymentStatusHistoryRepository.save(
                PaymentStatusHistoryRecord.failure(
                    savedPayment.id(),
                    null, // no previous status
                    "VALIDATION_FAILED",
                    ruleEngine.aggregateErrorMessage(validationResults),
                    "SYSTEM"
                )
            );
            return savedPayment;
        }
    }
    
    /**
     * Retrieve a payment by ID.
     * 
     * @param paymentId payment ID
     * @return Payment record, or empty if not found
     */
    public Optional<PaymentRecord> getPaymentById(Long paymentId) {
        return paymentRepository.findById(paymentId);
    }
    
    /**
     * Retrieve a payment's complete audit trail (all status transitions).
     * 
     * @param paymentId payment ID
     * @return List of status history records in chronological order
     */
    public List<PaymentStatusHistoryRecord> getPaymentHistory(Long paymentId) {
        return paymentStatusHistoryRepository.findByPaymentId(paymentId);
    }
    
    /**
     * Retrieve validation results for a payment.
     * Shows which rules were executed and which ones failed (if any).
     * 
     * @param paymentId payment ID
     * @return List of validation result records
     */
    public List<ValidationResultRecord> getValidationResults(Long paymentId) {
        return validationResultRepository.findByPaymentId(paymentId);
    }
    
    /**
     * List all payments with optional filtering.
     * 
     * @param status filter by status (null = no filter)
     * @param limit max results
     * @param offset pagination offset
     * @return List of payment records
     */
    public List<PaymentRecord> listPayments(PaymentStatus status, int limit, int offset) {
        return paymentRepository.findAll(status, limit, offset);
    }
    
    /**
     * List payments with advanced filtering and pagination.
     * Supports multiple filter criteria: status, account, currency, date range, failed rule.
     * 
     * @param status filter by payment status (null = no filter)
     * @param account filter by source or destination account (null = no filter)
     * @param currency filter by currency (null = no filter)
     * @param dateFrom filter by created_at >= dateFrom (null = no filter)
     * @param dateTo filter by created_at <= dateTo (null = no filter)
     * @param failedRuleId filter by failed validation rule ID (null = no filter)
     * @param limit max results
     * @param offset pagination offset
     * @return List of payment records matching all provided filters
     */
    public List<PaymentRecord> listPaymentsFiltered(
        PaymentStatus status,
        String account,
        String currency,
        LocalDateTime dateFrom,
        LocalDateTime dateTo,
        Long failedRuleId,
        int limit,
        int offset
    ) {
        return paymentRepository.findAllFiltered(status, account, currency, dateFrom, dateTo, failedRuleId, limit, offset);
    }
    
    /**
     * Validate and transition a payment to a new status.
     * 
     * Enforces state machine rules:
     * - CREATED → VALIDATED or FAILED
     * - VALIDATED → SENT or FAILED
     * - SENT → COMPLETED or FAILED
     * - COMPLETED/FAILED → (no transitions allowed)
     * 
     * @param paymentId payment ID
     * @param newStatus desired status
     * @return updated payment record
     * @throws IllegalArgumentException if payment not found
     * @throws IllegalStateException if transition not allowed
     */
    public PaymentRecord transitionPayment(Long paymentId, PaymentStatus newStatus) {
        // 1. Retrieve payment
        PaymentRecord payment = paymentRepository.findById(paymentId)
            .orElseThrow(() -> new IllegalArgumentException("Payment not found: " + paymentId));
        
        PaymentStatus currentStatus = payment.status();
        
        // 2. Validate transition is allowed
        StatusTransitionValidator.validateTransition(currentStatus, newStatus);
        
        // 3. Update payment status
        PaymentRecord updatedPayment = payment.withStatus(newStatus);
        PaymentRecord savedPayment = paymentRepository.update(updatedPayment);
        
        // 4. Log status transition to history
        paymentStatusHistoryRepository.save(
            PaymentStatusHistoryRecord.transition(
                paymentId,
                currentStatus,
                newStatus,
                "API" // Triggered by API call
            )
        );
        
        return savedPayment;
    }
    
    /**
     * Mark a payment as failed with error details.
     * Can be called from any status to immediately move to FAILED.
     * 
     * @param paymentId payment ID
     * @param errorCode error code
     * @param errorMessage error message
     * @return updated payment record
     * @throws IllegalArgumentException if payment not found
     */
    public PaymentRecord failPayment(Long paymentId, String errorCode, String errorMessage) {
        // 1. Retrieve payment
        PaymentRecord payment = paymentRepository.findById(paymentId)
            .orElseThrow(() -> new IllegalArgumentException("Payment not found: " + paymentId));
        
        PaymentStatus currentStatus = payment.status();
        
        // 2. Check if current status is terminal (can't fail an already complete/failed payment)
        if (currentStatus == PaymentStatus.COMPLETED || currentStatus == PaymentStatus.FAILED) {
            throw new IllegalStateException(
                String.format("Cannot fail a payment in %s status", currentStatus)
            );
        }
        
        // 3. Update payment with error details
        PaymentRecord failedPayment = payment.withFailure(errorCode, errorMessage);
        PaymentRecord savedPayment = paymentRepository.update(failedPayment);
        
        // 4. Log failure to history
        paymentStatusHistoryRepository.save(
            PaymentStatusHistoryRecord.failure(
                paymentId,
                currentStatus,
                errorCode,
                errorMessage,
                "SYSTEM"
            )
        );
        
        return savedPayment;
    }
    
    /**
     * Count total payments.
     * 
     * @return count of all payments
     */
    public long countPayments() {
        return paymentRepository.count();
    }
    
    /**
     * Count payments by status.
     * 
     * @param status payment status
     * @return count of payments with that status
     */
    public long countPaymentsByStatus(PaymentStatus status) {
        return paymentRepository.countByStatus(status);
    }
    
    /**
     * Process a VALIDATED payment to SENT status in its own transaction.
     * 
     * CRITICAL: This method uses @Transactional(propagation = Propagation.REQUIRES_NEW)
     * which ensures this payment is processed in a NEW, independent transaction.
     * 
     * Benefits:
     * - If this method succeeds, changes are committed immediately
     * - If this method fails, ONLY this transaction is rolled back
     * - Other payments processed by the scheduler are NOT affected
     * - Scheduler can continue processing other payments even if this one fails
     * 
     * This is essential for batch processing scenarios where one failure should not
     * cascade to previously processed items.
     * 
     * @param paymentId payment ID to process
     * @return updated payment record with SENT status
     * @throws IllegalArgumentException if payment not found
     * @throws IllegalStateException if transition not allowed
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public PaymentRecord processValidatedPaymentToSent(Long paymentId) {
        // Retrieve payment within this new transaction
        PaymentRecord payment = paymentRepository.findById(paymentId)
            .orElseThrow(() -> new IllegalArgumentException("Payment not found: " + paymentId));
        
        // Validate and transition to SENT
        return transitionPayment(paymentId, PaymentStatus.SENT);
    }
    
    /**
     * Process a SENT payment to COMPLETED status in its own transaction.
     * 
     * CRITICAL: This method uses @Transactional(propagation = Propagation.REQUIRES_NEW)
     * which ensures this payment is processed in a NEW, independent transaction.
     * 
     * See processValidatedPaymentToSent() for detailed explanation of benefits.
     * 
     * @param paymentId payment ID to process
     * @return updated payment record with COMPLETED status
     * @throws IllegalArgumentException if payment not found
     * @throws IllegalStateException if transition not allowed
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public PaymentRecord processSentPaymentToCompletion(Long paymentId) {
        // Retrieve payment within this new transaction
        PaymentRecord payment = paymentRepository.findById(paymentId)
            .orElseThrow(() -> new IllegalArgumentException("Payment not found: " + paymentId));
        
        // Validate and transition to COMPLETED
        return transitionPayment(paymentId, PaymentStatus.COMPLETED);
    }
    
    /**
     * Mark a SENT payment as FAILED in its own transaction.
     * 
     * CRITICAL: This method uses @Transactional(propagation = Propagation.REQUIRES_NEW)
     * which ensures this payment is processed in a NEW, independent transaction.
     * 
     * See processValidatedPaymentToSent() for detailed explanation of benefits.
     * 
     * @param paymentId payment ID to fail
     * @param errorCode error code
     * @param errorMessage error message
     * @return updated payment record with FAILED status
     * @throws IllegalArgumentException if payment not found
     * @throws IllegalStateException if payment is already in terminal state
     */
     @Transactional(propagation = Propagation.REQUIRES_NEW)
    public PaymentRecord processSentPaymentFailure(Long paymentId, String errorCode, String errorMessage) {
        // Retrieve payment within this new transaction
        PaymentRecord payment = paymentRepository.findById(paymentId)
            .orElseThrow(() -> new IllegalArgumentException("Payment not found: " + paymentId));
        
        // Mark as failed
        return failPayment(paymentId, errorCode, errorMessage);
    }
}
